version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.7.3-stretch
      - image: wurstmeister/zookeeper
        name: zookeeper
      - image: wurstmeister/kafka:2.12-2.1.0
        name: kafka
        environment:
          KAFKA_ADVERTISED_HOST_NAME: kafka
          KAFKA_ADVERTISED_PORT: 9092
          KAFKA_PORT: 9092
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_DELETE_TOPIC_ENABLE: true

    steps:
      - checkout

      - run:
          name: Wait for kafka to start up
          command: |
            sleep 25


      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install .[kafka]
            python component-tests/kafka/publisher.py
